Add common_ancestor function
EcoJulia/Phylo.jl pull request #41
Opened 2021-01-13 11:00 UTC by mkborregaard

Adds a new metrics.jl file which currently only has a function to identify the most recent common ancestor. See discusion at #40. 

@tpoisot I've branched off your master branch, is that OK? 
@isaacovercast would you mind testing?

2021-01-13 15:58 UTC, isaacovercast commented
@mkborregaard Tested and it works, or at least it agrees with the MRCA for the code I wrote. Thanks!

2021-01-13 16:02 UTC, mkborregaard commented
How do the speeds stack up in a real-world example?

2021-01-13 17:02 UTC, isaacovercast commented
Yours is faster ;)

Mine:
```
@benchmark getmrca(tre, names, false)
BenchmarkTools.Trial: 
  memory estimate:  25.05 KiB
  allocs estimate:  321
  --------------
  minimum time:     40.762 μs (0.00% GC)
  median time:      45.852 μs (0.00% GC)
  mean time:        49.266 μs (5.21% GC)
  maximum time:     8.681 ms (99.20% GC)
  --------------
  samples:          10000
  evals/sample:     1
```
Yours:
```
@benchmark common_ancestor(tre, names)
BenchmarkTools.Trial: 
  memory estimate:  3.58 KiB
  allocs estimate:  31
  --------------
  minimum time:     6.989 μs (0.00% GC)
  median time:      7.741 μs (0.00% GC)
  mean time:        8.462 μs (4.22% GC)
  maximum time:     1.822 ms (99.05% GC)
  --------------
  samples:          10000
  evals/sample:     4
```

2021-01-13 22:11 UTC, richardreeve requested changes
I think the test may fail if we change anything about the parsing, so I've suggested a change. The other issue is with naming - I've no problem in principle with `common_ancestor`, but it's not consistent with what we've done in the rest of the package - I'd go for `commonancestor` for `mrca` probably...

2021-01-13 23:04 UTC, mkborregaard commented on src/Phylo.jl
> +export common_ancestor
`commonancestor` is hard to read though. Maybe `mrca` is well-established enough as a term?

2021-01-13 23:05 UTC, mkborregaard commented on src/Phylo.jl
> +export common_ancestor
I'll change it to whatever you suggest @richardreeve and then go ahead and merge if that's OK

2021-01-13 23:11 UTC, mkborregaard commented on src/Phylo.jl
> +export common_ancestor
This seems to indicate that `mrca`should work
![Skærmbillede 2021-01-14 kl  00 11 03](https://user-images.githubusercontent.com/8429802/104521366-0ee66880-55fd-11eb-82b5-6d3d71796ca5.png)

2021-01-13 23:21 UTC, richardreeve commented on src/Phylo.jl
> +export common_ancestor
I think mrca is fine for anyone doing phylogenetics. Tbh, when I saw "common ancestor", I had to translate it into mrca in my head!

2021-01-14 14:58 UTC, richardreeve approved these changes

2021-01-14 16:04 UTC, mkborregaard commented
tests fail on 1.0 because of JuliaDB - do we care?

2021-01-14 16:04 UTC, merged

2021-01-14 23:39 UTC, richardreeve commented
No, @claireh93 is preparing a separate PR part of which will remove the 1.0 tests.